'use client';

export default function Projects() {
  return (
    <section id="projects" className="py-20 px-4"><div className="max-w-5xl mx-auto"><h2 className="text-3xl font-bold text-white mb-8">Projects</h2><div className="grid md:grid-cols-2 gap-6">
            <div key="Zenflow - Clinical Workflow & Provider Management Dashboard" className="bg-gray-800 rounded-lg p-6"><h3 className="text-xl font-semibold text-white">Zenflow - Clinical Workflow & Provider Management Dashboard</h3><p className="text-gray-400 mt-2">Architected a comprehensive SaaS dashboard for healthcare provider management, designed to optimize clinical workflow efficiency and practitioner coordination. Engineered a low-latency, dynamic weekly scheduling calendar grid that effectively manages simultaneous multi-practitioner time slots and real-time appointment statuses (Ongoing, Pending, Cancelled). Integrated secure operational metrics tables, modular analytics panels, and detailed partner/corporate client views to monitor overall practitioner utilization and performance.</p></div>
            <div key="Solitare - Premium Headless E-Commerce Jewelry Platform" className="bg-gray-800 rounded-lg p-6"><h3 className="text-xl font-semibold text-white">Solitare - Premium Headless E-Commerce Jewelry Platform</h3><p className="text-gray-400 mt-2">Developed a high-performance, responsive headless e-commerce interface optimized for media-rich luxury catalog interaction and brand discovery. Implemented advanced localized category filters (Bangles, Necklaces, Rings, etc.), persistent client-side states, high-fidelity item grids, and intuitive customer favorites/wishlist functionalities. Optimized modern asset delivery networks and lazy-loading mechanisms, achieving a notable 35% improvement in First Contentful Paint (FCP) across high-resolution product showcase nodes.</p></div>
            <div key="Pizza – Real-Time Hospitality Outlet Management Application" className="bg-gray-800 rounded-lg p-6"><h3 className="text-xl font-semibold text-white">Pizza – Real-Time Hospitality Outlet Management Application</h3><p className="text-gray-400 mt-2">Engineered a tablet-optimized real-time outlet operations and layout management dashboard, specifically designed to minimize operational friction in high-volume dining environments. Developed an interactive live floor-plan manager leveraging persistent state updates to accurately map table statuses (Vacant, Occupied, Overdue) and integrate automated alert systems. Established a centralized telemetry pipeline displaying key performance metrics (Average Table Turnaround Time and Average Queue Time), which successfully lowered seating friction intervals by 18%.</p></div>
            <div key="Trinity – Personalized Mental Health & Wellness Mobile Application" className="bg-gray-800 rounded-lg p-6"><h3 className="text-xl font-semibold text-white">Trinity – Personalized Mental Health & Wellness Mobile Application</h3><p className="text-gray-400 mt-2">Designed and developed a user-centric cross-platform mobile application focused on mental well-being, behavioral habits, and telehealth access. Implemented a highly interactive daily mood journaling module featuring specialized feedback components and micro-interactions, which elevated user retention metrics by 22%. Established encrypted synchronization endpoints to ensure secure user data transmission, facilitate self-assessments, and streamline clinical consultation appointment booking.</p></div>
          </div></div></section>
  );
}
